name: Continuous Integration

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version-file: .nvmrc
        # node-version: 24
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: latest
    - name: Install dependencies
      run: pnpm install --yes

    # - name: Install build tools for native modules (better-sqlite3 issue /1)
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y build-essential python3
    # - name: Rebuild better-sqlite3 for the current Node version (better-sqlite3 issue /2)
    #   run: pnpm rebuild better-sqlite3

    # - name: Setup Biome
    #   uses: biomejs/setup-biome@v2
    #   with:
    #     # version: latest
    #     version: 2.0.0
    - name: Run Biome
      run: pnpm biome:ci
      # run: biome ci ./src ./tests
    - name: Run tests
      run: pnpm test
